# Site settings
title: 隨 bang 寫程式
description: 部落格
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://vuncrychen.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: vuncrychen
user_description: 天涯何處無程式, 何必單戀一行碼
user_title: 
email: vuncrychen2002@gmail.com
twitter_username: topchen5
github_username:  vuncrychen
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 主頁
    url: /blog
  - title: 分類
    url: /blog/series
  - title: 標籤
    url: /blog/tags
  - title: 關於
    url: /blog/about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
