# Site settings
title: 隨 bang 寫程式
description: 部落格
baseurl: "https://vuncrychen.github.io/" # the subpath of your site, e.g. /blog
url: "https://vuncrychen.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: vuncrychen
user_description: 天涯何處無程式, 何必單戀一行碼
user_title: 歡迎您!
email: vuncrychen2002@gmail.com
twitter_username: topchen5
github_username:  vuncrychen
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: Search
    url: /search

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

tipue_search:
    include:
        pages: false
        collections: []
    exclude:
        files: [search.html, index.html, tags.html]
        categories: []
        tags: []
